return {
  -- add gruvbox
  -- { "olimorris/onedarkpro.nvim" },
  -- { "talha-akram/noctis.nvim" },
  -- { "gbprod/nord.nvim" },
  -- Configure LazyVim to load gruvbox
  {
    "LazyVim/LazyVim",
    opts = {
      -- colorscheme = "onedark",
      -- colorscheme = "onedark_vivid",
      -- colorscheme = "onedark_dark",
      -- colorscheme = "noctis",
      -- colorscheme = "noctis_azureus",
      -- colorscheme = "nord",
      -- colorscheme = "catppuccin",
      -- colorscheme = "catppuccin-frappe",
      colorscheme = "catppuccin-mocha",
      -- colorscheme = "catppuccin-macchiato",
      -- integrations = {
      --   aerial = true,
      --   alpha = true,
      --   cmp = true,
      --   dashboard = true,
      --   flash = true,
      --   gitsigns = true,
      --   headlines = true,
      --   illuminate = true,
      --   indent_blankline = { enabled = true },
      --   leap = true,
      --   lsp_trouble = true,
      --   mason = true,
      --   markdown = true,
      --   mini = true,
      --   native_lsp = {
      --     enabled = true,
      --     underlines = {
      --       errors = { "undercurl" },
      --       hints = { "undercurl" },
      --       warnings = { "undercurl" },
      --       information = { "undercurl" },
      --     },
      --   },
      --   navic = { enabled = true, custom_bg = "lualine" },
      --   neotest = true,
      --   neotree = true,
      --   noice = true,
      --   notify = true,
      --   semantic_tokens = true,
      --   telescope = true,
      --   treesitter = true,
      --   treesitter_context = true,
      --   which_key = true,
      -- },
    },
  },
}
