return {
  { "rcarriga/nvim-notify", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "dstein64/vim-startuptime", enabled = false },
  { "Exafunction/codeium.nvim", enabled = false },
  { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
}
